DROP DATABASE IF EXISTS granaconta;
CREATE DATABASE granaconta;

USE granaconta;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    rendaMensal DECIMAL(10,2) NOT NULL
);
